// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpm240_IyF6VL-1fmLxyOsSlYSgLle6uo',
    appId: '1:498273498378:web:2491d98c4643d27e0876f3',
    messagingSenderId: '498273498378',
    projectId: 'chat-7199f',
    authDomain: 'chat-7199f.firebaseapp.com',
    databaseURL: 'https://chat-7199f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-7199f.firebasestorage.app',
    measurementId: 'G-NYWLR5CF32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb9QahSJWGKIkZX9kKCPdUa3StM1u_31E',
    appId: '1:498273498378:android:ba7a5c03b151fb150876f3',
    messagingSenderId: '498273498378',
    projectId: 'chat-7199f',
    databaseURL: 'https://chat-7199f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-7199f.firebasestorage.app',
  );
}
